# Generated by Django 2.1 on 2019-01-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authot',
            new_name='author',
        ),
    ]
