# Generated by Django 2.1 on 2019-01-18 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_homepageitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageItems',
        ),
    ]
